config {
  type: "operations",
  hasOutput: true,
  dependencies: ["node_classes", "edge_rules"]
}

CREATE OR REPLACE PROPERTY GRAPH ${self()}
  NODE TABLES (
    ${ref("node_classes")} KEY (uri)
  )
  EDGE TABLES (
    ${ref("edge_rules")} KEY (edge_id)
      SOURCE KEY (source_uri) REFERENCES ${ref("node_classes")} (uri)
      DESTINATION KEY (target_uri) REFERENCES ${ref("node_classes")} (uri)
  );
