config {
  type: "operations",
  hasOutput: true,
  schema: "kg_graph_data",
  name: "global_nodes",
  description: "Unified table for all graph nodes."
}

CREATE TABLE IF NOT EXISTS ${self()} (
    node_id STRING NOT NULL,
    file_id STRING,
    page_num INT64,
    name STRING,
    ontology_class STRING,
    properties STRING,
    unbound_insights ARRAY<STRUCT<insight_description STRING, inferred_category STRING>>,
    embedding ARRAY<FLOAT64>
);