dataformCoreVersion: 3.0.48
defaultProject: "your-project-id"
defaultLocation: us
defaultDataset: dataform
defaultAssertionDataset: dataform_assertions
vars:
  project_id: "your-project-id"
  location: "us-central1"
  connection_id: "your-project-id.us.kg_knowledge_hub_conn"
  ontology_cache_id: "your-vertex-cache-id"
  gcs_bucket: "your-bucket-name"
  bq_region: "us"
